### ISSUE TITLE
not working bro

### ISSUE THREAD

**Issue by realglitch** [malokhvii-eduard/bulk-sms#7]

**Comment by malokhvii-eduard** [comment]
@realglitch Hi, thank you for your issue. Can you describe the issue, add steps to reproduce and so on?

**Comment by realglitch** [comment]
I've connected my device to adb and when I send a message nothing delivers or sends it just says that it does

**Comment by malokhvii-eduard** [comment]
@realglitch Which Android version do you have? Did you do all the preparation steps?
